steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=$_CIPHERTEXTFILE
      - --plaintext-file=service-account.json
      - --location=global
      - --keyring=$_KEYRING
      - --key=$_KEY

  - name: node:10.15.1
    entrypoint: yarn
    args: ['install']

  - name: node:10.15.1
    entrypoint: yarn
    args: ['add', 'firebase-tools']

  - name: node:10.15.1
    entrypoint: yarn
    args: ['add', 'firebase-functions']

  - name: node:10.15.1
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - '_F_APIKEY=$_F_APIKEY'
      - '_F_AUTHDOMAIN=$_F_AUTHDOMAIN'
      - '_F_DATABASEURL=$_F_DATABASEURL'
      - '_F_PROJECTID=$_F_PROJECTID'
      - '_F_STORAGEBUCKET=$_F_STORAGEBUCKET'
      - '_F_APPID=_F_APPID'
      - '_F_MEASUREMENTID=$_F_MEASUREMENTID'
      - '_STRIPE_PUBLISHABLE_KEY=$_STRIPE_PUBLISHABLE_KEY'
      - '_STRIPE_SECRET_KEY=$_STRIPE_SECRET_KEY'

  - name: node:10.15.1
    entrypoint: yarn
    args: ['build']

  - name: 'node:10.15.1'
    entrypoint: './node_modules/.bin/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--token', '$_TOKEN']
